channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _r-mutex=1.0.1
  - adjusttext=0.7.3.1
  - alabaster=0.7.12
  - anndata=0.7.5
  - anndata2ri=1.0.6
  - anyio=2.0.2
  - appdirs=1.4.4
  - appnope=0.1.2
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - babel=2.9.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bbknn=1.4.1
  - beautifulsoup4=4.9.3
  - bioconductor-annotationdbi=1.52.0
  - bioconductor-beachmat=2.6.0
  - bioconductor-biobase=2.50.0
  - bioconductor-biocgenerics=0.36.0
  - bioconductor-biocneighbors=1.8.0
  - bioconductor-biocparallel=1.24.0
  - bioconductor-biocsingular=1.6.0
  - bioconductor-bluster=1.0.0
  - bioconductor-clusterprofiler=3.18.1
  - bioconductor-delayedarray=0.16.0
  - bioconductor-delayedmatrixstats=1.12.0
  - bioconductor-do.db=2.9
  - bioconductor-dose=3.16.0
  - bioconductor-edger=3.32.0
  - bioconductor-enhancedvolcano=1.8.0
  - bioconductor-enrichplot=1.10.2
  - bioconductor-fgsea=1.16.0
  - bioconductor-genomeinfodb=1.26.0
  - bioconductor-genomeinfodbdata=1.2.4
  - bioconductor-genomicranges=1.42.0
  - bioconductor-go.db=3.12.1
  - bioconductor-gosemsim=2.16.0
  - bioconductor-hdf5array=1.18.0
  - bioconductor-iranges=2.24.0
  - bioconductor-limma=3.46.0
  - bioconductor-matrixgenerics=1.2.0
  - bioconductor-qvalue=2.22.0
  - bioconductor-rhdf5=2.34.0
  - bioconductor-rhdf5filters=1.2.0
  - bioconductor-rhdf5lib=1.12.0
  - bioconductor-s4vectors=0.28.0
  - bioconductor-scater=1.18.0
  - bioconductor-scran=1.18.0
  - bioconductor-scuttle=1.0.0
  - bioconductor-singlecellexperiment=1.12.0
  - bioconductor-slingshot=1.8.0
  - bioconductor-sparsematrixstats=1.2.0
  - bioconductor-stringdb=2.2.2
  - bioconductor-summarizedexperiment=1.20.0
  - bioconductor-xvector=0.30.0
  - bioconductor-zlibbioc=1.36.0
  - bioinfokit=2.0.4
  - bioservices=1.7.11
  - bleach=3.2.2
  - blosc=1.21.0
  - bokeh=2.3.1
  - brotlipy=0.7.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2022.6.15
  - cached-property=1.5.1
  - cairo=1.16.0
  - cctools_osx-64=949.0.1
  - cellrank=1.2.0
  - celltypist=0.1.5
  - certifi=2021.5.30
  - cffi=1.14.4
  - chardet=4.0.0
  - clang=11.0.1
  - clang-11=11.0.1
  - clang_osx-64=11.0.1
  - clangxx=11.0.1
  - clangxx_osx-64=11.0.1
  - click=8.0.1
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - colorcet=2.0.6
  - colorlog=4.7.2
  - colormath=3.0.0
  - compiler-rt=11.0.1
  - compiler-rt_osx-64=11.0.1
  - contextvars=2.4
  - cryptography=3.3.1
  - curl=7.71.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2021.1.1
  - dataclasses=0.7
  - decorator=4.4.2
  - defusedxml=0.6.0
  - descartes=1.1.0
  - docrep=0.3.2
  - docutils=0.16
  - easydev=0.10.1
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - fbpca=1.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - future=0.18.2
  - future_fstrings=1.2.0
  - geosketch=1.2
  - get_version=2.1
  - gettext=0.19.8.1
  - gevent=21.1.2
  - gfortran_impl_osx-64=9.3.0
  - gfortran_osx-64=9.3.0
  - gmp=6.2.1
  - graphite2=1.3.13
  - greenlet=0.4.17
  - grequests=0.6.0
  - gseapy=0.10.3
  - gsl=2.6
  - h5py=3.1.0
  - harfbuzz=2.7.4
  - harmonypy=0.0.5
  - hdf5=1.10.6
  - holoviews=1.14.3
  - html5lib=1.1
  - hvplot=0.7.1
  - hypre=2.18.2
  - icu=68.1
  - idna=2.10
  - imageio=2.9.0
  - imagesize=1.2.0
  - immutables=0.14
  - importlib-metadata=3.4.0
  - importlib_metadata=3.4.0
  - ipykernel=5.4.3
  - ipython=7.12.0
  - ipython-sql=0.3.9
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - isl=0.22.1
  - jedi=0.10.2
  - jinja2=2.11.3
  - joblib=1.0.0
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.11
  - jupyter_core=4.7.0
  - jupyter_server=1.2.2
  - jupyterlab=3.0.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.1.2
  - jupyterlab_widgets=1.0.2
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lcms2=2.11
  - ld64_osx-64=530
  - ldid=2.1.2
  - legacy-api-wrap=1.2
  - leidenalg=0.8.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang-cpp11=11.0.1
  - libcurl=7.71.1
  - libcxx=11.0.1
  - libdeflate=1.0
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran-devel_osx-64=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.66.4
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libllvm11=11.0.1
  - libnghttp2=1.41.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libuv=1.41.0
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.10
  - libxslt=1.1.33
  - llvm-openmp=11.0.1
  - llvm-tools=11.0.1
  - llvmlite=0.35.0
  - loompy=3.0.6
  - louvain=0.7.0
  - lxml=4.6.2
  - lz4-c=1.9.3
  - make=4.3
  - markdown=3.3.4
  - markupsafe=1.1.1
  - matplotlib=3.3.3
  - matplotlib-base=3.3.3
  - matplotlib-venn=0.11.6
  - metis=5.1.0
  - mistune=0.8.4
  - mizani=0.7.3
  - mock=4.0.3
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpi=1.0
  - mpi4py=3.1.1
  - mumps-include=5.2.1
  - mumps-mpi=5.2.1
  - natsort=7.1.1
  - nbclassic=0.2.6
  - nbclient=0.5.1
  - nbformat=5.1.2
  - ncls=0.0.57
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - networkx=2.5
  - nodejs=15.11.0
  - notebook=6.2.0
  - numba=0.52.0
  - numexpr=2.7.2
  - numpy=1.19.5
  - numpy_groupies=0.9.13
  - numpydoc=1.1.0
  - olefile=0.46
  - openmpi=4.1.0
  - openpyxl=3.0.9
  - openssl=1.1.1q
  - packaging=20.8
  - palettable=3.3.0
  - pandas=1.1.5
  - pandoc=2.11.3.2
  - pandocfilters=1.4.2
  - panel=0.11.2
  - pango=1.42.4
  - param=1.10.1
  - parmetis=4.0.3
  - parso=0.8.1
  - patsy=0.5.1
  - pbr=5.6.0
  - pcre=8.44
  - pcre2=10.36
  - petsc=3.14.5
  - petsc4py=3.14.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.0
  - pip=21.0
  - pixman=0.40.0
  - plotnine=0.8.0
  - prettytable=2.1.0
  - progressbar2=3.53.1
  - proj=7.2.0
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.13
  - prompt_toolkit=3.0.13
  - pthread-stubs=0.4
  - ptscotch=6.0.9
  - ptyprocess=0.7.0
  - pycairo=1.20.0
  - pycparser=2.20
  - pyct=0.4.6
  - pyct-core=0.4.6
  - pygam=0.8.0
  - pygments=2.7.4
  - pygpcca=1.0.2
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyranges=0.0.92
  - pyrle=0.0.31
  - pyrsistent=0.17.3
  - pysam=0.15.3
  - pysocks=1.7.1
  - pytables=3.6.1
  - python=3.6.12
  - python-annoy=1.17.0
  - python-dateutil=2.8.1
  - python-igraph=0.8.3
  - python-utils=3.1.0
  - python_abi=3.6
  - pytz=2020.5
  - pyviz_comms=2.0.1
  - pywavelets=1.1.1
  - pyyaml=5.4.1
  - pyzmq=20.0.0
  - r=4.0
  - r-abind=1.4_5
  - r-ape=5.4_1
  - r-ash=1.0_15
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.2.1
  - r-base=4.0.3
  - r-base64enc=0.1_3
  - r-beeswarm=0.3.1
  - r-bh=1.75.0_0
  - r-biocmanager=1.30.15
  - r-bit=4.0.4
  - r-bit64=4.0.5
  - r-bitops=1.0_6
  - r-blob=1.2.1
  - r-boot=1.3_27
  - r-brio=1.1.1
  - r-broom=0.7.5
  - r-bslib=0.2.4
  - r-cachem=1.0.4
  - r-cairo=1.5_12.2
  - r-callr=3.5.1
  - r-caret=6.0_86
  - r-catools=1.18.1
  - r-cellranger=1.1.0
  - r-chron=2.3_56
  - r-class=7.3_18
  - r-cli=2.3.1
  - r-clipr=0.7.1
  - r-cluster=2.1.1
  - r-codetools=0.2_18
  - r-colorspace=2.0_2
  - r-commonmark=1.7
  - r-cowplot=1.1.1
  - r-cpp11=0.2.6
  - r-crayon=1.4.1
  - r-crosstalk=1.1.1
  - r-curl=4.3
  - r-data.table=1.14.0
  - r-dbi=1.1.1
  - r-dbplyr=2.1.0
  - r-deldir=0.2_10
  - r-desc=1.2.0
  - r-diffobj=0.3.3
  - r-digest=0.6.27
  - r-downloader=0.4
  - r-dplyr=1.0.4
  - r-dqrng=0.2.1
  - r-ellipsis=0.3.1
  - r-evaluate=0.14
  - r-extrafont=0.17
  - r-extrafontdb=1.0
  - r-fansi=0.4.2
  - r-farver=2.1.0
  - r-fastmap=1.1.0
  - r-fastmatch=1.1_0
  - r-fitdistrplus=1.1_3
  - r-fnn=1.1.3
  - r-forcats=0.5.1
  - r-foreach=1.5.1
  - r-foreign=0.8_81
  - r-formatr=1.8
  - r-fs=1.5.0
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-future=1.21.0
  - r-future.apply=1.7.0
  - r-generics=0.1.0
  - r-ggalt=0.4.0
  - r-ggbeeswarm=0.6.0
  - r-ggforce=0.3.3
  - r-ggplot2=3.3.3
  - r-ggraph=2.0.5
  - r-ggrastr=0.2.3
  - r-ggrepel=0.9.1
  - r-ggridges=0.5.3
  - r-globals=0.14.0
  - r-glue=1.4.2
  - r-goftest=1.2_2
  - r-gower=0.2.2
  - r-gplots=3.1.1
  - r-gprofiler2=0.2.1
  - r-graphlayouts=0.7.1
  - r-gridextra=2.3
  - r-gsubfn=0.7
  - r-gtable=0.3.0
  - r-gtools=3.8.2
  - r-harmony=0.1
  - r-hash=3.0.1
  - r-haven=2.3.1
  - r-hexbin=1.28.2
  - r-highr=0.8
  - r-hms=1.0.0
  - r-htmltools=0.5.1.1
  - r-htmlwidgets=1.5.3
  - r-httpuv=1.5.5
  - r-httr=1.4.2
  - r-ica=1.0_2
  - r-igraph=1.2.6
  - r-ipred=0.9_11
  - r-irlba=2.3.3
  - r-isoband=0.2.3
  - r-iterators=1.0.13
  - r-jquerylib=0.1.3
  - r-jsonlite=1.7.2
  - r-kernlab=0.9_29
  - r-kernsmooth=2.23_18
  - r-knitr=1.31
  - r-labeling=0.4.2
  - r-lambda.r=1.2.4
  - r-later=1.1.0.1
  - r-lattice=0.20_41
  - r-lava=1.6.9
  - r-lazyeval=0.2.2
  - r-leiden=0.3.7
  - r-lifecycle=1.0.0
  - r-listenv=0.8.0
  - r-lmtest=0.9_38
  - r-locfit=1.5_9.4
  - r-lsei=1.3_0
  - r-lubridate=1.7.10
  - r-magrittr=2.0.1
  - r-maps=3.3.0
  - r-markdown=1.1
  - r-mass=7.3_53.1
  - r-matrix=1.3_2
  - r-matrixstats=0.58.0
  - r-memoise=2.0.0
  - r-mgcv=1.8_34
  - r-mime=0.10
  - r-miniui=0.1.1.1
  - r-mlmetrics=1.1.1
  - r-modelmetrics=1.2.2.2
  - r-modelr=0.1.8
  - r-munsell=0.5.0
  - r-nlme=3.1_152
  - r-nnet=7.3_15
  - r-npsurv=0.5_0
  - r-numderiv=2016.8_1.1
  - r-openssl=1.4.3
  - r-parallelly=1.23.0
  - r-patchwork=1.1.1
  - r-pbapply=1.4_3
  - r-pillar=1.5.0
  - r-pkgbuild=1.2.0
  - r-pkgconfig=2.0.3
  - r-pkgload=1.2.0
  - r-plogr=0.2.0
  - r-plotly=4.9.3
  - r-plotrix=3.8_2
  - r-plyr=1.8.6
  - r-png=0.1_7
  - r-polyclip=1.10_0
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-princurve=2.1.6
  - r-proc=1.17.0.1
  - r-processx=3.4.5
  - r-prodlim=2019.11.13
  - r-progress=1.2.2
  - r-proj4=1.0_10.1
  - r-promises=1.2.0.1
  - r-proto=1.0.0
  - r-ps=1.6.0
  - r-purrr=0.3.4
  - r-r6=2.5.0
  - r-ragg=0.4.0
  - r-rann=2.6.1
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.6
  - r-rcppannoy=0.0.18
  - r-rcpparmadillo=0.10.2.1.0
  - r-rcppeigen=0.3.3.9.1
  - r-rcpphnsw=0.3.0
  - r-rcppparallel=5.0.3
  - r-rcppprogress=0.4.2
  - r-rcurl=1.98_1.2
  - r-readr=1.4.0
  - r-readxl=1.3.1
  - r-recipes=0.1.15
  - r-recommended=4.0
  - r-rematch=1.0.1
  - r-rematch2=2.1.2
  - r-reprex=1.0.0
  - r-reshape2=1.4.4
  - r-reticulate=1.18
  - r-rlang=0.4.10
  - r-rmarkdown=2.7
  - r-rocr=1.0_11
  - r-rpart=4.1_15
  - r-rprojroot=2.0.2
  - r-rspectra=0.16_0
  - r-rsqlite=2.2.3
  - r-rstudioapi=0.13
  - r-rsvd=1.0.3
  - r-rtsne=0.15
  - r-rttf2pt1=1.3.8
  - r-rvcheck=0.1.8
  - r-rvest=1.0.0
  - r-sass=0.3.1
  - r-scales=1.1.1
  - r-scattermore=0.7
  - r-scatterpie=0.1.6
  - r-scpred=v1.9.0
  - r-sctransform=0.3.2
  - r-selectr=0.4_2
  - r-seurat=3.2.3
  - r-seuratobject=4.0.0
  - r-shadowtext=0.0.8
  - r-shiny=1.6.0
  - r-sitmo=2.0.1
  - r-snow=0.4_3
  - r-sourcetools=0.1.7
  - r-spatial=7.3_13
  - r-spatstat=1.64_1
  - r-spatstat.data=2.0_0
  - r-spatstat.utils=2.0_0
  - r-sqldf=0.4_11
  - r-squarem=2021.1
  - r-statmod=1.4.36
  - r-stringi=1.5.3
  - r-stringr=1.4.0
  - r-survival=3.2_7
  - r-sys=3.4
  - r-systemfonts=1.0.1
  - r-tensor=1.5
  - r-testthat=3.0.2
  - r-textshaping=0.1.2
  - r-tibble=3.1.0
  - r-tidygraph=1.2.0
  - r-tidyr=1.1.3
  - r-tidyselect=1.1.0
  - r-tidyverse=1.3.0
  - r-timedate=3043.102
  - r-tinytex=0.30
  - r-tweenr=1.0.1
  - r-utf8=1.1.4
  - r-uwot=0.1.10
  - r-vctrs=0.3.6
  - r-vipor=0.4.5
  - r-viridis=0.5.1
  - r-viridislite=0.3.0
  - r-waldo=0.2.4
  - r-withr=2.4.1
  - r-xfun=0.20
  - r-xml2=1.3.2
  - r-xtable=1.8_4
  - r-yaml=2.2.1
  - r-zeallot=0.1.0
  - r-zoo=1.8_8
  - readline=8.0
  - requests=2.25.1
  - requests-cache=0.5.0
  - rpy2=3.4.2
  - scalapack=2.0.2
  - scanpy=1.7.1
  - scikit-image=0.16.2
  - scikit-learn=0.24.1
  - scipy=1.5.3
  - scotch=6.0.9
  - scrublet=0.2.3
  - scvelo=0.2.4
  - seaborn=0.11.1
  - seaborn-base=0.11.1
  - send2trash=1.5.0
  - setuptools=49.6.0
  - setuptools-scm=5.0.1
  - setuptools_scm=5.0.1
  - simplegeneric=0.8.1
  - sinfo=0.3.1
  - six=1.15.0
  - slepc=3.14.0
  - slepc4py=3.14.0
  - sniffio=1.2.0
  - snowballstemmer=2.1.0
  - sorted_nearest=0.0.31
  - soupsieve=2.0.1
  - spectra=0.0.11
  - sphinx=3.4.3
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlalchemy=1.3.23
  - sqlalchemy-migrate=0.13.0
  - sqlite=3.34.0
  - sqlparse=0.4.1
  - statsmodels=0.12.1
  - stdlib-list=0.7.0
  - suds-jurko=0.6
  - suitesparse=5.6.0
  - superlu=5.2.2
  - tabulate=0.8.7
  - tapi=1100.0.11
  - tbb=2020.2
  - tempita=0.5.3dev
  - terminado=0.9.2
  - testpath=0.4.4
  - texttable=1.6.3
  - textwrap3=0.9.2
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tktable=2.10
  - tokenize-rt=4.2.1
  - toml=0.10.2
  - toolz=0.11.1
  - tornado=6.1
  - tqdm=4.56.0
  - traitlets=4.3.3
  - typing_extensions=3.7.4.3
  - tzlocal=2.1
  - umap-learn=0.4.6
  - urllib3=1.26.2
  - velocyto.py=0.17.17
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - xlrd=2.0.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxt=1.2.1
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zope.event=4.5.0
  - zope.interface=5.2.0
  - zstd=1.4.8
  - pip:
    - adobo==0.2.57
    - datatable==0.11.1
    - fa2==0.3.5
    - intervaltree==2.1.0
    - jupyter-contrib-core==0.4.0
    - jupyter-contrib-nbextensions==0.5.1
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-latex-envs==1.4.6
    - jupyter-nbextensions-configurator==0.5.0
    - mnnpy==0.1.9.5
    - mplcursors==0.4
    - nbconvert==5.6.1
    - psutil==5.8.0
    - python-louvain==0.15
    - scanorama==1.7
    - sccaf==0.0.10
    - sortedcontainers==2.3.0
